### ISSUE TITLE
Add an option to stop the daemon

### ISSUE THREAD

**Issue by psimonazzi** [puniverse/capsule-daemon#2]
The daemon capsule can be used to start a daemon on Linux with JSVC, but it has no option to stop it. Currently, the daemon can be stopped by sending a signal or using JSVC stop command.
A capsule command option to stop the daemon could be useful.

**Comment by circlespainter** [comment]
Updated `0.2.0-SNAPSHOT` uploaded on Sonatype. Thanks for the issue!
