### ISSUE TITLE
How the tool should behaves ?

### ISSUE THREAD

**Issue by ihommani** [puniverse/capsule-daemon#7]
Hi, 

I am trying to wrap a capsule with the capsule daemon, but the behavior I get is rather odd. 
No process seems to be spawned although launching the capsule containing the main class works.

Here the log I get with the command line inside. 
[log.txt](https://files.zenhub.io/56c452d25d3a5c4e4bb3b8e7)

The log is telling me about a bin folder and a pid file, that I can't find. 
I'm running on an Archlinux 4.3.3-2-ARCH

The capsule I want to launch is a spring-boot application. 
What I expect from using the capsule-daemon is to launch the spring  boot application's capsule as a daemon.
Is it possible ? 

Thx for your help.

**Comment by circlespainter** [comment]
Sure, have you tried running with the `-Dcapsule.daemon.debug=true` flag? There are also a few important notes to take into account, towards the end of the `README`:

> - `jsvc` with default settings (due to the default PID file location) and `procrun` in any case (for service installation, uninstallation and upgrade) require resp. `root` and administrative privileges.
> - Launch, Java and service execution users must all be able to access the same Capsule's cache directory. You can set it to a commonly accessible location (for example in `/tmp/capsule`) through the `CAPSULE_CACHE_DIR` environment variable.

**Comment by ihommani** [comment]
Indeed I get more info with the debug flag. Thx for the tip.
Daemon loader seems to be found, and daemon loaded suscessfully.
However it can't start and fail on an InvocationTargetException.

Launching the capsule alone works. From what I read in the error stack trace, the problem comes from the application contained in the 'main' capsule. 
What do you think ,?
[log.txt](https://github.com/puniverse/capsule-daemon/files/135348/log.txt)

Could it be linked to lack of rights on jsvc ?

**Comment by circlespainter** [comment]
The ultimate cause seems to be an exception thrown by your app's main ("Caused by: `org.springframework.boot.devtools.restart.SilentExitExceptionHandler$SilentExitException`"), maybe related to some Spring Boot development-time auto-restart mechanism (I'm not very knowledgeable about Spring Boot)?

**Comment by rmuchall** [comment]
I'm new to capsule-daemon so I might be wrong but could it be that you don't have the correct privileges to correctly access the capsule temporary directory?

From the Readme:
https://github.com/puniverse/capsule-daemon/blob/master/README.md
> Launch, Java and service execution users must all be able to access the same Capsule's cache directory. You can set it to a commonly accessible location (for example in /tmp/capsule) through the CAPSULE_CACHE_DIR environment variable.

**Comment by ihommani** [comment]
Alright. Yes seems like it's due to Spring boot plumbery. 
The last error I got is related to a failure when starting the embeded Tomcat.

Have you encountered previously this specific case where a capsuled application spawns an embeded server to serve itself ?

**Comment by circlespainter** [comment]
Yes sure, I usually run tests about capsules and caplets also with [quasar-stocks](https://github.com/circlespainter/quasar-stocks) which is an embedded server too.

**Comment by ihommani** [comment]
Ok, it's working now. I think that the tomcat startup was failing because the port on which it wanted to start was alredy taken.
Thx for the support.
