### ISSUE TITLE
Add Daemon-User as a system property

### ISSUE THREAD

**Issue by rmuchall** [puniverse/capsule-daemon#9]
Hi circlespainter,

I have another feature/suggestion:
It would be useful to be able to override the Daemon-User manifest property by using a system property. This would allow for different users depending on the server that the daemon is running.

e.g.
Windows) -Dcapsule.service.user=WindowsUser
Unix) -Dcapsule.service.user=UnixUser

Thanks! :)

**Comment by circlespainter** [comment]
Hi, there were some mistakes in the README that made it difficult to spot it but there's already `capsule.daemon.user` that can override `Daemon-User`.

**Comment by rmuchall** [comment]
Thanks circlespainter! :)
